name: Build and Release

on:
  push:
    tags:
      - 'v*'   # Trigger on tags like v1.0.9, v2.0.0 etc.

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'   # adjust to your target .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o out

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CnyThbConverter
          path: out/*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: CnyThbConverter
          path: out

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: out/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
