name: Build and Release WPF App

on:
  push:
    tags:
      - 'v*'           # build whenever you push a tag like v1.0.9
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore

      - name: Publish (self-contained EXE)
        run: >
          dotnet publish CnyThbConverter.csproj -c Release -r win-x64
          --self-contained true
          -p:PublishSingleFile=true
          -p:PublishTrimmed=false

      - name: Archive build output
        uses: actions/upload-artifact@v4
        with:
          name: CnyThbConverter-win-x64
          path: bin/Release/net9.0-windows/win-x64/publish/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: CnyThbConverter-win-x64
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**
