name: Build and Release WPF App
on:
  push:
    tags: [ 'v*' ]  #eg. v1.0.0
  workflow_dispatch: {}
permissions:
  contents: write   #permission

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore

      - name: Publish (self-contained single EXE)
        run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true

      - name: Debug list publish output
        run: |
          echo "Workspace: $Env:GITHUB_WORKSPACE"
          dir bin\Release\net9.0-windows\win-x64\publish

      - name: Create/Update Release & Upload EXE
        uses: softprops/action-gh-release@v2
        with:
          files: bin/Release/net9.0-windows/win-x64/publish/*.exe
          fail_on_unmatched_files: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  #token with permision
