name: Build and Release WPF App

on:
  push:
    tags: [ 'v*' ]        # works when you push a tag like v1.0.3
  workflow_dispatch: {}    # lets you click "Run workflow" without a tag

permissions:
  contents: write        # permission

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      # If manually triggered, create a tag automatically on the current commit
      - name: Ensure tag exists (only for manual runs)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/github-script@v7
        id: mk_tag
        with:
          script: |
            const now = new Date();
            const pad = n => String(n).padStart(2,'0');
            const tag = `v-${now.getUTCFullYear()}${pad(now.getUTCMonth()+1)}${pad(now.getUTCDate())}-${pad(now.getUTCHours())}${pad(now.getUTCMinutes())}${pad(now.getUTCSeconds())}`;
            const sha = context.sha;
            await github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${tag}`,
              sha
            });
            core.setOutput('tag', tag);

      - name: Compute TAG_NAME
        shell: pwsh
        run: |
          if ("${{ github.ref_type }}" -eq "tag") {
            echo "TAG_NAME=${{ github.ref_name }}" | Out-File -FilePath $env:GITHUB_ENV -Append
          } else {
            echo "TAG_NAME=${{ steps.mk_tag.outputs.tag }}" | Out-File -FilePath $env:GITHUB_ENV -Append
          }

      - name: Restore
        run: dotnet restore

      - name: Publish (self-contained single EXE)
        run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true

      # rename the exe for a nicer file name with version/tag
      - name: Rename EXE
        shell: pwsh
        run: |
          $pub = "bin/Release/net9.0-windows/win-x64/publish"
          $exe = Get-ChildItem "$pub/*.exe" | Select-Object -First 1
          if (-not $exe) { throw "No .exe found in $pub" }
          $new = Join-Path $pub ("CNY-THB-Converter-" + "${{ env.TAG_NAME }}" + ".exe")
          Copy-Item $exe.FullName $new
          Write-Host "Renamed to $new"

      - name: Create/Update Release & Upload EXE
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}               # <= provide the tag explicitly
          name: Release ${{ env.TAG_NAME }}
          files: bin/Release/net9.0-windows/win-x64/publish/CNY-THB-Converter-*.exe
          fail_on_unmatched_files: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
