name: Build and Release WPF App

on:
  push:
    tags:
      - 'v*' # Runs only when you push a tag starting with "v" (e.g., v1.0.0)

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Release
        run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true

      - name: Upload Build Artifact to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            CnyThbConverter/bin/Release/net9.0-windows/win-x64/publish/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Built-in token, no PAT required
